### ISSUE TITLE
Switch off automatic interpolation for bounding box coordinates

### ISSUE THREAD

**Issue by manybodycpa** [openvinotoolkit/cvat#1282]
Edited:

I'm predicting annotations with external models and save them as tracks in CVAT XML format. I want to edit/improve these tracks using CVAT. However, when I upload my results, I need to make all frames key frames to avoid automatic (and, in my case, often less accurate) interpolation of the bounding boxes. At the same time, I would like to use keep the interpolation feature for other attributes of the labels (properties that only change on key frames).

How can I disable interpolation for the box coordinates but not for the other attributes?

(I'm note sure if such a feature warrants an official solution but would very much appreciate a quick pointer regarding how to to this myself for now by changing the source code.)

**Comment by azhavoro** [comment]
Hi, sorry for the late response.
I think it is not so easy to implement, because you need to modify frontend and backends parts (the same interpolation algorithm is used for dumping annotations).
Server implementation is here https://github.com/openvinotoolkit/cvat/blob/a222741f6b3c9fea4f363f475ef9fcd4a85c6a7d/cvat/apps/dataset_manager/annotation.py#L448
@bsekachev could you please comment and maybe add some hints about UI implementations?

**Comment by bsekachev** [comment]
I agree with @azhavoro, it isn't easy to implement because of used architecture approaches. One idea I have is to add feature ``re-calculate interpolation`` between two keyframes (all the keyframes between are still keyframes, but them position is automatically changed according to selected right and left keyframes). In this case only client part need to be modified.

**Comment by nmanovic** [comment]
@manybodycpa , it looks like the request is very specific. You can try to contribute the functionality. For now I will close the issue.
