### ISSUE TITLE
Cancelling 'Create New Task' does not have effect. 

### ISSUE THREAD

**Issue by Paperone80** [openvinotoolkit/cvat#205]
Hi,

I pulled the cvat version from 2018-11-19. 

When creating a new task via 'Submit' button with Source: Shared, the 'Cancel' button in the 'Task Configuration' dialog has no effect. 

The dialog window disappears but when clicking 'Create New Task' the 'Task Configuration' dialog reappears and it is still copying or compressing the images.

**Comment by bsekachev** [comment]
The issue was relevant on previous UI version.
Now CVAT has different approach when creating a task (we do not use dialog windows and we do not have cancel button now). Also it was not explained clearly what behavior expected when reopen creating page.

Because of this reasons I'll close the issue. Do not hesitate comment and reopen it if you mean it is still relevant.
