### ISSUE TITLE
CVAT Docker file issue- /tmp/requirements/sampleconfig.txt

### ISSUE THREAD

**Issue by poojitha102424** [openvinotoolkit/cvat#2120]
My actions before raising this issue
 Read/searched the documents
 Searched past issues

I am trying to build an image from docker file using docker build.We have passed values to USER and django configurations in the arguments ,But docker-build" fails at ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/tmp/requirements/sampleconfig.txt'.

Kindly help me to resolve this issue.

<img width="937" alt="CVAT issue" src="https://user-images.githubusercontent.com/56558252/92104663-421f1c80-edff-11ea-92cb-0a94a459ee5e.PNG">

**Comment by azhavoro** [comment]
Did I understand you correctly that you tried to build cvat image with `docker build` command instead of using `docker-compose` as mentioned on the installation guide?

Please provide steps to reproduce (exact command you used to build and version of CVAT `git log -1`).

P.S. Could you please describe why docker-compose is not suitable for you?

**Comment by poojitha102424** [comment]
Thank you for your reply
we were trying to build the cvat-server and cvat-ui images separately. hence, we were using docker build command but with docker-compose build it works.
I will try with docker compose

**Comment by azhavoro** [comment]
You can build images separately with the following command `docker-compose build cvat` or `docker-compose build cvat_ui`

**Comment by azhavoro** [comment]
Can I close the issue?

**Comment by poojitha102424** [comment]
i can able to build the images using docker-compose build cvat or docker-compose build cvat_ui
Thank you . you can close the issue
