### ISSUE TITLE
Error: Request failed with status code 500. "KeyError: 'tf_detection_api'\n".

### ISSUE THREAD

**Issue by patankar-anant123** [openvinotoolkit/cvat#2248]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs):
Steps:
1) install CVAT tool on Ubuntu
2) Restart PC/System
3) Run CVAT Tool
4) Try to export or dump dataset as Tfrecords

### Your Environment
Operating System: Ubuntu 20.04 LTS

![Screenshot from 2020-09-30 20-31-26](https://user-images.githubusercontent.com/12649913/94704600-b517a680-035d-11eb-87ef-068bce75994a.png)

**Comment by zhiltsov-max** [comment]
Hi, do you have tensorflow installed?

**Comment by nmanovic** [comment]
@zhiltsov-max , can you reproduce the behaviors?

**Comment by zhiltsov-max** [comment]
There is not enough information to reproduce.

**Comment by nmanovic** [comment]
@patankar-anant123 , don't hesitate to re-open the issue if you can provide more information how to reproduce the issue.

**Comment by jaharkes** [comment]
I just had the same error message and digging through the logs it looked like the main cvat container was unable to talk to redis. According to `docker-compose ps` all containers were running normally, but this was after a server reboot, so I assume docker brought the containers back up instead of docker-compose and something must have been a little off.

I restarted everything with `docker-compose down ; docker-compose up -d` and tfrecord downloads started working again.
