### ISSUE TITLE
Question related to increasing number of label id and task number

### ISSUE THREAD

**Issue by GoGoPen** [openvinotoolkit/cvat#2324]
When I create new task with labels, the CVAT will automatically create new id for each label I created. I deleted the task after annotation was finished. 

Then, when I create new task with same set of labels' name, the label id will increase which ignores the fact that those old labels already exist. There is another problem. When I have deleted the old tasks, the task number keeps increasing. I would like to know if there is any proper way to delete old task and old label without completely deleting all the volumes ?
Thanks.

**Comment by azhavoro** [comment]
Please use Gitter for such questions next time.

IDs for the task (and labels) are generated by the database and it's expected behavior: explanation is here https://wiki.postgresql.org/wiki/FAQ#Why_are_there_gaps_in_the_numbering_of_my_sequence.2FSERIAL_column.3F_Why_aren.27t_my_sequence_numbers_reused_on_transaction_abort.3F

Task and label linked with one to many relationship, so each label can be related only with one task. So, increasing of label ID is expected behavior too.
So, deleting the task with UI is the proper way to delete it and it removes all related data from the filesystem and the database.

Does it answer your question?

**Comment by GoGoPen** [comment]
> Please use Gitter for such questions next time.
> 
> IDs for the task (and labels) are generated by the database and it's expected behavior: explanation is here https://wiki.postgresql.org/wiki/FAQ#Why_are_there_gaps_in_the_numbering_of_my_sequence.2FSERIAL_column.3F_Why_aren.27t_my_sequence_numbers_reused_on_transaction_abort.3F
> 
> Task and label linked with one to many relationship, so each label can be related only with one task. So, increasing of label ID is expected behavior too.
> So, deleting the task with UI is the proper way to delete the task and it removes all related data from the filesystem and the database.
> 
> Does it answer your question?

Thank you very much for your answering. It is highly appreciated !
