### ISSUE TITLE
Cannot upload YOLO annotations generated from dump annotations

### ISSUE THREAD

**Issue by kairikibear** [openvinotoolkit/cvat#2473]
### My actions before raising this issue
- [V ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [V ] Searched [past issues](/issues)

I have a dataset i want to label, but i want to incorporate exisitng labels of the dataset (detection dataset, i want to add attributes)

I experimented to see if it was possible through the upload annotation feature and did exactly this :
1. Created a small toy dataset
2. Labelled the images
3. Saved the annots
4. Dump the annotations to yolo format
5. Upload again with yolo format

And instead of working as intended, i have met with this error : 
![image](https://user-images.githubusercontent.com/70246267/99949507-bab5c980-2dad-11eb-9b1a-41d4a0f98525.png)

I immediately checked the log and traced the error all the way to this [file](https://github.com/openvinotoolkit/datumaro/blob/develop/datumaro/plugins/yolo_format/extractor.py#L156)

in which i surmise the error comes from the absence of the 'size' property of 'image' being None, which is funnily caused by the absence of an images.meta file judging from these [lines](https://github.com/openvinotoolkit/datumaro/blob/develop/datumaro/plugins/yolo_format/extractor.py#L48-L60), documented nowhere. 

I also thought that somehow i did something that makes image info is not passed to the constructor of the extractor, but seems like [this](https://github.com/openvinotoolkit/datumaro/blob/b71610368e7eb7a3b63aea74d228a7e0aca1eddc/datumaro/components/project.py#L318) shows it was not the case.

### Expected Behaviour

The yolo annotation can be uploaded normally without anything on the way.

### Current Behaviour

The error aforementioned

### Possible Solution

Better documentations regarding such subjects if it was NOT documented, or bugfix if it was a bug / error

### Steps to Reproduce (for bugs)

Mentioned above

### Your Environment

This commit hash 3fb3f677ebf95ed90ff404fb9ffe52f3c8fe55b3
Website says version 1.1rc0

**Comment by zhiltsov-max** [comment]
Hi.
It is more of a bug than something undocumented, because this image information is passed [here](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/dataset_manager/formats/yolo.py#L37-L49) and the user is not expected to provide it. Could you help with reproducing this issue? How did you add images to the task?

**Comment by kairikibear** [comment]
Thanks for the response! I uploaded the image directly using the direct file upload and nothing else out of ordinary

**Comment by dyt811** [comment]
Reproduced the issue using a small 5 images test data set in both Win10 / Ubuntu20 OS (I was originally hoping to incorporate my new label txt files are Windows based and I thought CRLF was originally the problem before running into this issue). 

Further testing in both OS suggests the issue is more than CRLF as default YOLO 1.1 label zip output from CVAT in YOLO 1.1 format cannot be imported back into itself even before I attempt to incorporate my own label. Built based on latest Master branch #916dd6d on both Ubuntu20 and Windows 10 host. 

Server version: 1.2
Core version: 3.10.0
Canvas version: 2.2.1
UI version: 1.13.3

**Comment by nmanovic** [comment]
@yasakova-anastasia , could you please take the issue and fix?

@DmitriyOparin , could you please add test?

**Comment by DmitriyOparin** [comment]
@nmanovic, yes, sure
