### ISSUE TITLE
K8s deploys nuclio problem

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [openvinotoolkit/cvat#2501]
I executed the following command：

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
nuctl deploy --project-name cvat \
    --path $SCRIPT_DIR/openvino/dextr/nuclio \
	--namespace nuclio \
	--kubeconfig /etc/kubernetes/admin.conf \
	--verbose
	--platform kube

The following log is printed：

20.11.30 16:56:43.055                     nuctl (D) Saving deployment logs
20.11.30 16:56:43.065    nuctl.platform.updater (I) Updating function {"name": "openvino-dextr"}

Error - NuclioFunction in unhealthy state:

Error - context deadline exceeded
    .../platform/kube/controller/nucliofunction.go:148

Call stack:
Failed to wait for function resources to be available
    .../platform/kube/controller/nucliofunction.go:148

    /nuclio/pkg/platform/kube/deployer.go:264

Call stack:
NuclioFunction in unhealthy state:

Error - context deadline exceeded
    .../platform/kube/controller/nucliofunction.go:148

Call stack:
Failed to wait for function resources to be available
    .../platform/kube/controller/nucliofunction.go:148

    /nuclio/pkg/platform/kube/deployer.go:264
Failed to wait for function readiness.

Pod logs:

* nuclio-openvino-dextr-55cf7cbcd8-pmq9f
Failed to read logs: container "nuclio" in pod "nuclio-openvino-dextr-55cf7cbcd8-pmq9f" is waiting to start: trying and failing to pull image

* Warning events:
Failed to pull image "cvat/openvino.dextr:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for cvat/openvino.dextr, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error: ErrImagePull
Error: ImagePullBackOff

    /nuclio/pkg/platform/kube/deployer.go:177
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:175
You have new mail in /var/spool/mail/root

I want to know how to solve

**Comment by azhavoro** [comment]
We don't currently provide any Kubernetes templates for CVAT deployment, so I cannot reproduce your issue. I guess the reason is `pull access is denied for cvat / openvino.dextr, the repository does not exist, or a" docker login "might be required: denied: The requested resource access is denied`, make sure the image can be pulled.

If you are working on deploying K8s, may I ask you to contribute this feature to the mainstream repository, improving the existing PR https://github.com/openvinotoolkit/cvat/pull/1962 by adding nuclio support?
