### ISSUE TITLE
Multi polygon object

### ISSUE THREAD

**Issue by cbasavaraj** [openvinotoolkit/cvat#2600]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Desired Feature
Hi, would it be possible to have the option to annotate a multi-polygon object? In my dataset, there is often one object passing in front of the other. The object that is behind can then by split into two or more parts, each of which can be represented using a polygon. The COCO format in fact does allow for this, as the segmentation mask is a list of polygons. 

In the UI, this option may be represented by a multi-polygon. Would this be possible? Thanks.

**Comment by zhiltsov-max** [comment]
Hi, directly this is only available in COCO format. You can join polygons into groups, they will be exported as a single group of polygons in COCO. If you add a `rectangle` in a group, it will be used as a `bounding box`, otherwise it will be computed from polygons, as well as `area`.
Formats with masks (`Segmentation Mask`, `MOTS`, `CamVid`) will convert such polygons to masks and export them as a single object. Splitted objects in masks will be imported as a group of polygons.
`CVAT for *` and `Datumaro` formats will export them as is - as annotations with `group` tag.

**Comment by cbasavaraj** [comment]
Thanks for the response. Will test out the group feature sometime soon.
