### ISSUE TITLE
annotator has permission to dump, upload, export annotation the task! How to remove this permission?

### ISSUE THREAD

**Issue by arasharchor** [openvinotoolkit/cvat#2681]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
To my understanding annotators may not have permission to dump, upload, export annotations of the task.
### Current Behaviour
Annotator can dump, upload or export the task. However, the annotator can not delete the task. How to remove the permission of upload, dump and dataset export from annotators?

**Comment by azhavoro** [comment]
@arasharchor Hi, it's expected behavior, why do you think that the annotator role should not have permissions for upload/dump actions? What is your use case?
The roles are defined here https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/authentication/auth.py,
you can change the endpoint permissions according to your preference: https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/engine/views.py#L695 https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/engine/views.py#L528

**Comment by arasharchor** [comment]
@azhavoro annotator can mistakenly upload old version annotations overwriting previous annotations which might be newer version. Where should I change in those scripts to remove the permission of upload from annotator? It is OK if annotators can dump annotations.

**Comment by asenyaev** [comment]
@azhavoro I've faced a similar issue when an observer has a permission to edit, save and dump annotations. Do you know how to fix it?

Release: **1.2.0**
