### ISSUE TITLE
Intelligent Scissors add documentation

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#2765]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Need to add a piece of documentation to the user guide about the feature of intelligent scissors #2689 (how to use, etc)

**Comment by nmanovic** [comment]
@aschernov , could you please look at the issue?

**Comment by aschernov** [comment]
@bsekachev , how can we test this function? Seems the tool hasn't been updated yet.

**Comment by bsekachev** [comment]
@aschernov The server was updated, Please, additional to the documentation provide a feedback to the feature (what is good, what is wrong, what errors you met, etc.)

**Comment by bsekachev** [comment]
@aschernov Fixed.

@azhavoro We have separated cvat-proxy for cvat.org and the internal server. I've updated them (to get opencv works), should we commit the changes or left it as is?

**Comment by aschernov** [comment]
**What is good:**

1. The tool is well-suited for annotation of complex shapes on a contrast background.
![1](https://user-images.githubusercontent.com/45849884/107763699-173adc00-6d40-11eb-991f-a4059ab01496.png)
![2](https://user-images.githubusercontent.com/45849884/107763758-24f06180-6d40-11eb-8f76-774568bf0d7b.png)
2. The main advantage of the tool is an option to see the final line and change the line in the process.
3. In comparison with the manual method, using the tool is much faster for creating lines with many points.
![3](https://user-images.githubusercontent.com/45849884/107763792-32a5e700-6d40-11eb-971b-59d5da373efb.png)
I suggest adding the option to create points (like in case with polygon drawing). It could be done in a following way: for example, holding the Shift key would make “intelligent scissors” function as a polygon thus the points would be connected by a straight line. This addition would allow to combine manual and automatic drawing.

**What is wrong:**

1. Fully finished polygons often have two points in one place
2. Sometimes there are strong deviations of automatically created line which are difficult to control because even the slightest cursor shift creates different lines
![opencv1](https://user-images.githubusercontent.com/45849884/107763935-68e36680-6d40-11eb-9fc5-112a84aac89e.gif)
3. It is necessary to add an option of "automatic bordering" for existing polygons. It would help in tasks where you need to allocate all objects in the frame without empty areas.
![4](https://user-images.githubusercontent.com/45849884/107764006-81538100-6d40-11eb-9562-cc1873e966ab.png)
![5](https://user-images.githubusercontent.com/45849884/107764023-86b0cb80-6d40-11eb-8ca2-bd55c37c7e52.png)
4. Sometimes when new points are created quickly, the following message is displayed:
_RuntimeError: float unrepresentable in integer range
 8111568 - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch._
5. The cursor and the square are poorly visible
6. It is necessary to add a limit to the possible size of the threshold or a warning about possible slowdown of the working process (when the action threshold is very big the performance is low).
7.  Due to the square shape of the action's threshold, it turns out that diagonal lines can be longer than horizontal and vertical ones. Perhaps, it would be better to develop an option to rotate the square or change the action's threshold shape to a circle instead of the square.

**Comment by bsekachev** [comment]
@aschernov  

Thanks for the feedback. I'll create a separate issue with these cons.

**Comment by bsekachev** [comment]
Created issue #2800
