### ISSUE TITLE
Export error when there are invalid polygons in the overlapping frames (shapely.errors.TopologicalError)

### ISSUE THREAD

**Issue by fengyach** [openvinotoolkit/cvat#2851]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Export of the datasets should go through without any issues.

### Current Behaviour

When there are invalid polygons in the overlapping frames, a notification pops out stating the export cannot be done, and an api call error stating: 
`
shapely.errors.TopologicalError: The operation 'GEOSIntersection_r' could not be performed
`
Therefore blocking the export.

(in frames that have no overlapping, the invalid polygon does not block the export)

### Possible Solution

- ignore the invalid polygon when calculating similarity
- add validity check in the UI to prevent any creation of invalid polygon in the first place

### Steps to Reproduce (for bugs)

1. create a new task.
1. set the overlap size to an integer that is greater or equal to 1.
1. in the **overlapping** frames, draw an invalid polygon (self-overlapping polygon).
1. save and export the task.

### Context

We need the exported points' coordinates for further ML model training.

### Your Environment

- Operating System and version (e.g. Linux, Windows, MacOS): MacOS 11

**Comment by bsekachev** [comment]
Hi, @fengyach 

Do you happen to know how can we create "invalid" polygon on UI?

**Comment by fengyach** [comment]
@bsekachev   Hello! thank you very much for your comment! I have an example here:
![image](https://user-images.githubusercontent.com/7123627/109196943-a7dfd600-779c-11eb-8f5f-cebeb0d456af.png)

Also,[ I have created a PR related to the issue](https://github.com/openvinotoolkit/cvat/pull/2852), some sort of 'quick fix', would it be possible if you could check it out as well?
Much much obliged!

**Comment by bsekachev** [comment]
Okay, got it. 

If we speak about polygons with intersections, they are legal in CVAT (at least we cannot call them invalid) and we should not prevent creating them on UI. 
I saw the PR but probably it should be reviewed by @zhiltsov-max  or @yasakova-anastasia because I mightn't have enough expertise in this code.

**Comment by Legor** [comment]
At least it has to be possible to export the annotations in any case. 
I'm currently in the situation that I can't export my annotations because of this. I have a larger image dataset with polygon track annotations and a segment overlap of 2. Whenever I try to export any kind of annotation format I get the mentioned `GEOSIntersection_r` error.
I triple checked every overlapping frame for "false" annotations, however didn't find any that look suspicious to me. It would also help, if at least the frame number where the error occurs would be mentioned in the error message.

I also tried to change the frame range of each segment to not include any overlapping frames numbers anymore, however to no avail.

How can I get to my annotations bypassing the web interface or this error in overlapping frames?

**Comment by fengyach** [comment]
> At least it has to be possible to export the annotations in any case.
> I'm currently in the situation that I can't export my annotations because of this. I have a larger image dataset with polygon track annotations and a segment overlap of 2. Whenever I try to export any kind of annotation format I get the mentioned `GEOSIntersection_r` error.
> I triple checked every overlapping frame for "false" annotations, however didn't find any that look suspicious to me. It would also help, if at least the frame number where the error occurs would be mentioned in the error message.
> 
> I also tried to change the frame range of each segment to not include any overlapping frames numbers anymore, however to no avail.
> 
> How can I get to my annotations bypassing the web interface or this error in overlapping frames?

Hello! this is fixed via PR 2852   :)
