### ISSUE TITLE
[Bug] The 'Tag' does not upload in CVAT for video 1.1 annotations.

### ISSUE THREAD

**Issue by DmitriyOparin** [openvinotoolkit/cvat#2923]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Rectangle and Tag annotations were uploaded.

### Current Behaviour

Rectangle annotation uploaded but Tag does not upload.

### Possible Solution

Fix this bug.

### Steps to Reproduce (for bugs)

1.Create task with several images.
2.Draw 'Rectangle' (track) and 'Tag' in first frame.
3.Dump CVAT for video 1.1 annotations.
4.Upload CVAT 1.1 annotations.

### Your Environment

- Git hash commit (`git log -1`): 62cc956967db2720d69c374e31ce8c85b575e429
- Docker version `docker version` (e.g. Docker 17.0.05): N/A
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by kirill-sizov** [comment]
The problem is that CVAT for Video 1.1 does not support tags for frames.
And I think, there is no particular use for support tagging each frame in a video.
But it will be useful to annotate intervals on video and this feature described in other issues: https://github.com/openvinotoolkit/cvat/issues/1228; https://github.com/openvinotoolkit/cvat/issues/2117.
