### ISSUE TITLE
Hole cutting in polygons

### ISSUE THREAD

**Issue by nstolyarov** [openvinotoolkit/cvat#2958]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

There is no way to cut holes in polygons. Sometimes there may be a foreign object on the surface to be marked, which must be removed. Now this can only be done using the complex action shown in the video. The same video shows an example of how this is done in other software. An attempt to add a separate class for marking in black (RGB 000) also failed, because CVAT does not display black on the result mask.

### Expected Behaviour
Get the ability to cut holes in polygons.

### Current Behaviour
No normal ability to cut holes in polygons.
### Possible Solution
This can be done, for example, by adding an operation to subtract one polygon from another. Alternatively, you can add the Background class, which can be used to mark up objects that are not subject to markup.

### Context
Cutting is a very common operation in our project. The current cutting method is very time consuming.
### Your Environment
- Git hash commit (`git log -1`): commit 7a2dcfff61626dbfdaa694127fc1cff8ee10e000 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Anastasia Yasakova <anastasia.yasakova@intel.com>
Date:   Tue Mar 9 10:41:33 2021 +0300
- Docker version `docker version` (e.g. Docker 17.0.05):  20.10.5
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): GNU/Linux Ubuntu
4.15.0-136-generic
x86_64
- Video: https://drive.google.com/file/d/1MxlHa8XMlC__-w4JoKXcQG0uDzaztdY6/view?usp=sharing

**Comment by bsekachev** [comment]
Hi, @nstolyarov 

Please, use additional "background" class to create "holes" in polygons. Just draw it over a polygon object and then dump ``.png`` masks. 

The idea is that polygon with a hole is not a polygon anymore, it is a mask or another complex object (we cannot represent holes using only coordinate number sequences). CVAT does not support masks and I do not expect it will in the nearest future (if only community is ready to contribute).

Currently I will close the issue because it is dublicate of #1849 and #2384.

**Comment by nstolyarov** [comment]
@bsekachev, thank you for answer. But as I said there is the problem with "background" class. It seems reasonable to use it, but when I add a label "background" (or any other name) with RGB(0,0,0) any other classes override this one on SegmentationClass mask if we dump annotations via Segmentation mask 1.1. Even if I move it to foreground with "+" hotkey.

**Comment by bsekachev** [comment]
@zhiltsov-max Could you please comment on this? 

I also tried to dump a task with a couple of polygons and in case of dumping to CVAT Images it works as expected, but in case of dumping to SegmentationMask I get an archive without any masks. 

[task_test-2021_03_17_07_58_07-segmentation mask 1.1.zip](https://github.com/openvinotoolkit/cvat/files/6154630/task_test-2021_03_17_07_58_07-segmentation.mask.1.1.zip)

**Comment by nstolyarov** [comment]
Here is some example:

**First three images show layers**
![1](https://user-images.githubusercontent.com/80746178/111442218-2a631200-8719-11eb-8552-188b8a6a7f39.png)
![2](https://user-images.githubusercontent.com/80746178/111442236-2e8f2f80-8719-11eb-8874-182eaa59f5a1.png)
![3](https://user-images.githubusercontent.com/80746178/111442265-37800100-8719-11eb-84df-3c5de0e64a5f.png)

**Actual segmentation. "background" label has RGB(0,0,0) color.**
![4](https://user-images.githubusercontent.com/80746178/111442280-3cdd4b80-8719-11eb-84cf-4a9117597d02.png)

**Result of Segmentation mask 1.1 dump**

_SegmentationClass_
![segclass](https://user-images.githubusercontent.com/80746178/111442291-4070d280-8719-11eb-98b9-474cd40c8cf8.png)

_SegmentationObject_
![segobject](https://user-images.githubusercontent.com/80746178/111442301-44045980-8719-11eb-9932-fbd6e4fd683a.png)

**Comment by nstolyarov** [comment]
Here is the second example but I have label "Trash" with RGB(1,1,1) instead of "background" RGB(0,0,0)

_SegmentationClass_
![trash_segclass](https://user-images.githubusercontent.com/80746178/111443654-a578f800-871a-11eb-95e0-0a3178733494.png)

_SegmentationObject_
![trash_segobject](https://user-images.githubusercontent.com/80746178/111443711-b1fd5080-871a-11eb-8576-ecc1d9a1ab1c.png)

It can work but you need to use other tools for changing pixels color after dump. Maybe it is not a bad idea to make "background" label be able in foreground layer?

**Comment by zhiltsov-max** [comment]
Currently in the develop branch it should be working this way:

Any class with the name `background` or with color (0, 0, 0) should fit. The "background" polygon was moved to foreground (+ or = key). The order of annotations is preserved, so being the latter annotation will work the same way.
![image](https://user-images.githubusercontent.com/13832349/111448252-49fd3900-871f-11eb-9d02-1a1716cf2b2f.png)

SegmentationClass
![image](https://user-images.githubusercontent.com/13832349/111448396-6b5e2500-871f-11eb-9cfb-5641e9c6492b.png)

SegmentationObject
![image](https://user-images.githubusercontent.com/13832349/111448764-cabc3500-871f-11eb-9caa-5c00c6f16c53.png)

Importing produces duplicated polygons.

**Comment by nstolyarov** [comment]
@zhiltsov-max could you please provide your commit id?

**Comment by zhiltsov-max** [comment]
83a08cb22fd8e7d9ec07ce090ebefd80672278e8, it should not be very different from the commit you used.

**Comment by zhiltsov-max** [comment]
@nstolyarov, can you check if the fix in https://github.com/openvinotoolkit/datumaro/pull/188 resolves the problem for you? It should allow exporting of masks with `background` class polygons on top of the other shapes to create holes in them. It should now work with both `SegmentationObject` and `SegmentationInstance` directories, instead of only `SegmentationObject`.

How to test:
1. Change this line: https://github.com/openvinotoolkit/cvat/blob/develop/cvat/requirements/base.txt#L53
  to `git+https://github.com/openvinotoolkit/datumaro@zm/holes-in-polygons`
2. Rebuild the container
3. Restart the server

Examples:

I have a task with such config:
![image](https://user-images.githubusercontent.com/13832349/112620922-2c745180-8e3a-11eb-9415-2647114fd176.png)
(where `background` has color `#000`)

![image](https://user-images.githubusercontent.com/13832349/112620754-00f16700-8e3a-11eb-915b-6b42dc3e9bfd.png)
![image](https://user-images.githubusercontent.com/13832349/112620818-0f3f8300-8e3a-11eb-999a-696a669a692d.png)


![image](https://user-images.githubusercontent.com/13832349/112621049-59c0ff80-8e3a-11eb-98f4-238dad8e5684.png)
![image](https://user-images.githubusercontent.com/13832349/112621346-af95a780-8e3a-11eb-931a-7b7c41c2634b.png)
(But they are different instances yet)

But you're right about high overhead of using this functionality.

**Comment by nstolyarov** [comment]
@zhiltsov-max, hi! I tried to do it but unfortunately I still have no "background" over objects of other classes. 

My steps:

1. I changed this line: https://github.com/openvinotoolkit/cvat/blob/develop/cvat/requirements/base.txt#L53 to git+https://github.com/openvinotoolkit/datumaro@zm/holes-in-polygons
2. I removed docker containers and images with `docker rm $(docker ps -a -q)` and `docker rmi $(docker images -q)` respectively
3. I rebuild and started the container with `docker-compose up --force-recreate`

Maybe I do something wrong when fully rebuilding containers?

**Comment by zhiltsov-max** [comment]
@nstolyarov, in step 3 try to rebuild with `docker-compose -f ./docker-compose.yml -f ./docker-compose.dev.yml up --build`

**Comment by nstolyarov** [comment]
@zhiltsov-max hi!
Thank you for this fix. Seems it works in the #3030 version. But is it ok that on instance mask "background" still has object labeling?

**Comment by zhiltsov-max** [comment]
@nstolyarov, thanks for testing and confirming it works in the `develop` branch of CVAT. The patch I mentioned above (https://github.com/openvinotoolkit/datumaro/pull/188) fixes the problem with instance masks. This patch is applied to the Datumaro subproject, which is used by CVAT, so it doesn't affect CVAT directly and requires an extra step (№1 above), unless it is applied and merged into CVAT.
