### ISSUE TITLE
Enable auto save by default.

### ISSUE THREAD

**Issue by fengyach** [openvinotoolkit/cvat#3094]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Hello dev team, we would like to suggest to enable auto save every 5 min functionality by default (because we think it would be a good way to prevent possible unexpected data loss).

### Current Behaviour

The "enable auto save" option in the setting is turned off by default. Therefore we have to check the box every time we log in.

### Context

Sometimes we experience some unexpected network interruptions or other situations, which could lead to data/annotation loss due to not having clicked the save button. It would be really helpful to have the auto save turned on by default, so we do not have to turn it on manually every time we log in as some people might forget to do so.

**Comment by bsekachev** [comment]
Hi @fengyach 

Enabling auto save by default is not always expected behavior (some changes might occur which user does not expect).
So, we cannot enable it by default every time. But starting from the patch #3017, you can save your client-settings in the browser cache. So, once enabling auto-save and pressing "Save" button is enough to enable auto save by default (when open another task or refresh a browser tab) at the same browser on the same machine. 

Might it solve your case?

**Comment by fengyach** [comment]
> Hi @fengyach
> 
> Enabling auto save by default is not always expected behavior (some changes might occur which user does not expect).
> So, we cannot enable it by default every time. But starting from the patch #3017, you can save your client-settings in the browser cache. So, once enabling auto-save and pressing "Save" button is enough to enable auto save by default (when open another task or refresh a browser tab) at the same browser on the same machine.
> 
> Might it solve your case?

Hello, I will let my teammates know about this, thank you very much!

**Comment by fengyach** [comment]
I will close this issue now, as the possible solution is mentioned above.
