### ISSUE TITLE
Annotation format descriptions

### ISSUE THREAD

**Issue by nikky4D** [openvinotoolkit/cvat#3103]
Hi,

Is there a summary of what the various annotation formats are? I am working with video annotation, so I have tracks and object bounding boxes or polygons. I have used the cvat xml for video, but I would like to try other annotation formats. 

However, I don't know which is for images and which is for videos, and what they each look like. Is it possible to supply a snapshot of what the data should look like when downloaded for videos/images as is done for the xml format?

**Comment by nmanovic** [comment]
@zhiltsov-max , could you please answer?

**Comment by zhiltsov-max** [comment]
Hi, you can find information about formats here: https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/dataset_manager/formats/README.md

If a format supports an annotation shape type, such annotations will be exported regardless of task type. If a format supports tracks natively, tracks will be exported, otherwise tracks will be split into separate annotations with a `track_id` attribute and then this attribute will be exported, if the format supports attributes. For example, in "COCO instances" we've added support for custom attributes, so they will be exported. Opposite, ICDAR will export boxes, but won't export attributes, because they are not supported there.

**Comment by nikky4D** [comment]
Thank you for the quick response. This is very helpful. Would it be possible to add a link to this in the user_manual, at the Downloading-annotation section? It would be helpful when figuring out which annotation format to use.

**Comment by lstlaure** [comment]
> Hi, you can find information about formats here: https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/dataset_manager/formats/README.md
> 
> If a format supports an annotation shape type, such annotations will be exported regardless of task type. If a format supports tracks natively, tracks will be exported, otherwise tracks will be split into separate annotations with a `track_id` attribute, and then this attribute will be exported, if the format supports attributes. For example, in "COCO instances" we've added support for custom attributes, so they will be exported. Opposite, ICDAR will export boxes, but won't export attributes, because they are not supported there.

It is great to have added a 'track_id' attribute in the annotation exported in the COCO format.  But is-there a way to upload these 'track_id'? When you try to upload a .json COCO annotation file that was generated with CVAT with these 'track_id' attributes, track ids seems to be ignored and they disappear. It seems that the 'Upload' COCO annotation does not support this added 'track_id' attribute. Am'I wrong, and if not, isit planned to be supported soon ?

Best regards,

**Comment by zhiltsov-max** [comment]
@lstlaure, currently, such option is not implemented, because this format is not supposed for tracks. It could be a feature request - for example, for an import option, when they are implemented in #2911 / #1804. 

As a workaround, you can try to convert your annotations with Datumaro to a format with tracks (`MOT` (boxes) and `MOTS` (masks, polygons) in 0.1.9) and import the resulting annotations.
```
pip install datumaro
datum convert -i coco.json -if coco -o mot_dataset -f mot_seq
```

https://github.com/openvinotoolkit/datumaro/blob/develop/docs/user_manual.md#convert-datasets

**Comment by Saharkakavand** [comment]
Dear @zhiltsov-max 
Would you let me know if I can save the data , so that the labels are in int16 using the cvat tool?
I have a cell dataset, that I want to use them for instance segmentation for Stardist and EmbedSeg networks.
Thanks

**Comment by zhiltsov-max** [comment]
@Saharkakavand, try the [MOTS](https://www.vision.rwth-aachen.de/page/mots) format.

**Comment by Saharkakavand** [comment]
> @Saharkakavand, try the [MOTS](https://www.vision.rwth-aachen.de/page/mots) format.
When I try to upload the previous dumped annotations, I got this error: 
Could not import the task
Error: Request failed with status code 500. "KeyError: \"There is no item named 'task.json' in the archive\"\n".

**Comment by zhiltsov-max** [comment]
Did you use "import annotations" button?
