### ISSUE TITLE
Update CVAT - uses an image, skipping

### ISSUE THREAD

**Issue by davodogster** [openvinotoolkit/cvat#3355]
I'm following this link to update CVAT from an old version (about 10 months old) to the latest version.
https://openvinotoolkit.github.io/cvat/docs/for-users/faq/

What exactly does it mean by "rebuild the CVAT docker images as usual"
Does it mean remove the docker images then build the new ones?

Because if I do it without removing the old docker images it says:

When I run docker build it says:
![image](https://user-images.githubusercontent.com/46079516/123022036-4289b200-d429-11eb-8e56-a7a7c7178b90.png)

I also want to restore my data which I've backed up.

**Comment by azhavoro** [comment]
Hi, your log is expected because some time ago CVAT docker images were published on docker hub and you don't need to build CVAT yourself. So, it look likes the update guide needs to be updated a bit. To backup/restore CVAT please follow this guide https://openvinotoolkit.github.io/cvat/docs/administration/advanced/backup_guide/ which should be up to date.

**Comment by yohann84L** [comment]
Hi, 
I'm having the same trouble. Tried to update CVAT to 2.0.0-alpha from 1.7.0, I have the `*** uses an image, skipping`. 
Then when I'm connecting to CVAT it is still 1.7.0. Should I delete the old image? Am I going to lose the data I had?
