### ISSUE TITLE
Draw default label

### ISSUE THREAD

**Issue by zlstl1** [openvinotoolkit/cvat#3496]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Thx, CVAT is greatest to me.

I have some question.

Can I draw default label each job?
I'm labeling people and stores.
Each person has a different label, but the store is always the same.
So, I want to draw a default store label for each job.
Anybody have advice for me?

### Current Behaviour

Manual Search & Google Search & Code Review

**Comment by bsekachev** [comment]
@zlstl1 

I am not sure I correctly understand your request. It would be great if you come up with an example
If the store is always the same, do you really need to annotate it?
Do you annotate the store on each frame?

**Comment by zlstl1** [comment]
Sorry for the lack of explanation.
Store data is used as metadata.

For example)
1. Person do the act of entering a store.

2. At this time, I want to label the store so that it can utilize the information of the store (classification of the store, attributes of the store, etc.).

3. But, the position of the store does not change with the fixed camera.

4. So I want to do fixed labeling for the each store and each frame.

![그림1](https://user-images.githubusercontent.com/35329451/127941313-0ff37b37-f89a-4308-80f9-49eaaff19566.png)


===============================================================================


![그림2](https://user-images.githubusercontent.com/35329451/127941317-bf8540a7-ca8b-4456-8d50-5a9a0977b758.png)

**Comment by bsekachev** [comment]
@zlstl1 w

Okay, thanks. Now I got it.

I see two options here. In both, you have a label "store" with all necessary attributes (all the information about the store you want to keep. As you told: classification of the store, attributes of the store, etc). 

Option 1. Is to use the track to annotate the store. You just create a track object on the first frame and it is automatically interpolated to the end of the video (keeping position and attributes on each frame). After it was annotated just lock it and hide it in order to remove unnecessary details from the image. Your dumped annotations will contain this object on each frame. \

Option 2. Is to use "Propagate" feature. Very similar to the previous, but you create a shape (not a track) on the first frame. Setup all the attributes, activate the object and click propagate (via UI, or using Ctrl+B hotkey). It creates copies of the object on the following frames. 

The difference between these two methods is that in the first case you have one object (if you change it somewhere in the middle, the change will affect other frames). In the second case, you have not linked shapes and changing one of them does not affect others.

**Comment by zlstl1** [comment]
Thank you for quick response.

I have one more question.

Example)
I have 100 video such as video_1, video_2, video_3 ...
Each video has the same background but only the person change.

In this case, store_1 is in the same location in video_1, video_2, video_3...
If I use the first option(use track), I have to draw 100 times.

Is it possibel to programmatically draw each store per video?

I hope it works like this)
When each video is loaded, I want store_1 to be automatically labeled in the location I specified.

Thx....

**Comment by zlstl1** [comment]
I found solution!

In my case)
1. I annotate store_1 and export as CVAT for video 1.1 from video_1.
2. And load CVAT for video 1.1 from video_2.
3. I anotated store_1 by track and now work fine

Everything thanks a lot and sorry about stupid question!!!
