### ISSUE TITLE
Is it possible to install cvat with docker on windows server 2016??

### ISSUE THREAD

**Issue by zlstl1** [openvinotoolkit/cvat#3528]
### Context

Is it possible to install cvat with docker on windows server 2016???

**Comment by azhavoro** [comment]
Hi, I have no experience with CVAT on Windows server 2016, but if Docker can be installed it is probably possible. Maybe someone from the community has such experience.

**Comment by nmanovic** [comment]
@zlstl1 , please try to install ubuntu 18.04 (https://ubuntu.com/wsl) and follow the tutorial: https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#windows-10. If it works, you are lucky.

I will close the issue because I don't know what the core team can add. Our Windows support is based on docker and wsl2.
