### ISSUE TITLE
Slow task creation

### ISSUE THREAD

**Issue by lolpa1n** [openvinotoolkit/cvat#3743]
There are two servers with a CVAT, on one a task for 40,000 frames is created in 10 minutes, on the other for 2-3 hours. What is the reason for this? with a long load, it writes that many keyframes have been detected and the old method will be used.

**Comment by bsekachev** [comment]
Do these servers have different CVAT versions?

**Comment by lolpa1n** [comment]
Slow is the latest version, fast is v1.1.0

**Comment by bsekachev** [comment]
Since 1.1.0 optimized data streaming process was introduced (using .zip or video chunks instead of passing frames one by one), during performing annotations. 
But, in order to get frames faster on client, CVAT needs to do some preparation work on creating task stage (preparing these chunks), what makes this process longer. 

For some videos it is possible to collect meta information and create chunks "on the fly" when requested. 
For some videos, like in your case, when few keyframes detected, the option above is not possible.
