### ISSUE TITLE
CVAT uses pdf2image (MIT-license) which uses poppler (GPL)

### ISSUE THREAD

**Issue by engineer-exercise** [openvinotoolkit/cvat#3809]
### I found a license risk

CVAT uses pdf2image library to convert PDF to image (.jpeg) in [PdfReader](https://github.com/openvinotoolkit/cvat/blob/d2c77394c264e2346fe4b1bb0d40760997c4e7a6/cvat/apps/engine/media_extractors.py#L209).
[pdf2image](https://github.com/Belval/pdf2image) is [MIT License](https://github.com/Belval/pdf2image/blob/master/LICENSE) but it uses [poppler-utils](https://en.wikipedia.org/wiki/Poppler_(software)) which is GPLv2 or v3.
CVAT also installs poppler-utils on [Dockerfile](https://github.com/openvinotoolkit/cvat/blob/d15a3199c2c6ebf56b5e57eb26a39e678a6d190e/Dockerfile#L90)

### Possible Solution
Get rids PdfReader codes of pdf2image and replace another library.
Or create options to exclude PdfReader.

### Context
Avoids viral license.

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
@engineer-exercise Thanks, there is no license issue because pdf2image is not linked (or is not import any modules) with GPL licensed components and calls at the command line https://github.com/Belval/pdf2image/blob/master/pdf2image/pdf2image.py#L186-L188 and https://github.com/Belval/pdf2image/blob/master/pdf2image/pdf2image.py#L204 
The same about usage of poppler-utils in the cvat code.
