### ISSUE TITLE
Shortcut for switch to interactors

### ISSUE THREAD

**Issue by ryanalexmartin** [openvinotoolkit/cvat#3845]
In the documentation here: https://openvinotoolkit.github.io/cvat/docs/manual/advanced/ai-tools/

I did not see any shortcut for switching the interactor tool.  I think it would be useful to have a shortcut for switching to that tool, but I'm not aware if there is one.  If there is, can it be added to the documentation here on this page?  

If there is not a shortcut, I can submit a pull request for adding one.

**Comment by bsekachev** [comment]
Hi @ryanalexmartin 

There are not any shortcuts to switching AI tools. I am not sure how it could be implemented efficiently. My ideas are:
1. In the most of cases people use only one interactor per task
2. If we add ability to switch interactors, why not add ability to switch detectors/trackers? (And switch between them)
3. It is not clear what interactor is currently selected because you need to open popover to see it (theoretically can be solved using some notifications/messages).

**Comment by nmanovic** [comment]
I believe the question was answered. I will close the issue.

**Comment by GeorgePearse** [comment]
I've created a new issue related to this about the fact that you exit SAM useage after every single annotation which slows things down a tonne.
