### ISSUE TITLE
upload annotations miss the track_id information

### ISSUE THREAD

**Issue by VisionZQ** [openvinotoolkit/cvat#4043]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
Hi, please provide version of cvat, and steps to reproduce the issue

**Comment by VisionZQ** [comment]
Hi, 
CVAT currently vision as follow shown.
![Screenshot from 2021-12-20 18-37-56](https://user-images.githubusercontent.com/22951577/146755269-c4bdfa28-646f-4cba-8626-52291020ca76.png)



I have generated the label file offline, however, when I upload to cvat toools, the track_id is miss and only bounding box and label correct
![Screenshot from 2021-12-20 18-48-02](https://user-images.githubusercontent.com/22951577/146755660-60b50d3e-24d1-419e-b24d-47cb59def708.png)

**Comment by azhavoro** [comment]
What label configuration did you use for this task? 
Also please take look at specifications of the supported formats https://openvinotoolkit.github.io/cvat/docs/manual/advanced/formats/

**Comment by azhavoro** [comment]
There is no response for a long time, let's close the issue. Don't hesitate to reopen if this issue is still actual for you.

**Comment by jf99** [comment]
Hello, I have the same problem. Please re-open the issue @azhavoro.

I can draw tracks in CVAT (notice the text "POINTS TRACK" on the left and the button to toggle the "outside" property):
![pointstrack](https://user-images.githubusercontent.com/7962377/177328649-65edf3bc-442b-4b4e-bae5-8406bb90d364.png)
I can also export them as [Datumaro 1.0](https://github.com/openvinotoolkit/cvat/files/9046390/track-test-github-datumaro.zip). Notice that the default.json file in the attached zip archive contains tags with the key "track_id". However, after I import the zip into CVAT again ("Upload annotations -> Datumaro 1.0") all that is left are point **shapes** (instead of point **tracks**).
![pointsshape](https://user-images.githubusercontent.com/7962377/177329796-b5960248-8a31-4610-9351-ed2c973310ff.png)
Exporting the labels once again will generate a JSON without track_id.

Server version: 2.1
Core version: 5.0.1
Canvas version: 2.13.2
UI version: 1.37.0
