### ISSUE TITLE
what is the difference between shape and track?

### ISSUE THREAD

**Issue by planetroger2020** [openvinotoolkit/cvat#4073]
Can anyone tell me what I should use for drawing bounding boxes. Shape or track?

**Comment by bsekachev** [comment]
Hi, it depends on your needs.
If you have a set of not related images, shape is your choise.
If you need to annotate a video, tracks are more powerful (using shapes is also possible). With tracks you do not need to annotate each frame because they can be interpolated. Please, refer to user guide for more details.

**Comment by planetroger2020** [comment]
I see. Thank you so much.
