### ISSUE TITLE
A Validator Group, Support for Validation and Automation of Job Assgning for Annotators & Validators

### ISSUE THREAD

**Issue by dev225reddys** [openvinotoolkit/cvat#851]
1. Another Role/Group in the Admin Section Called "Validator" for Maintaining users who only wants to validate the Annotation.
2. A New UI for Validators which will have Something like "Correct/Wrong" options (No access to Annotation UI), and that job will be assigned back to Annotator for Corrections.
3. Finally, As we already have Role/Groups, Some kind of Tracker which keeps track of Annotators as well as jobs and automatically Assigns jobs to Annotators and Validators.

*2nd issued already, but for Classification of Images but not for Validation of Annotation.

**Comment by nmanovic** [comment]
We are going to have more advanced roles and organizations. We will not have an explicit validator. Any person who is assigned on a job, can validate the corresponding task. I will close the issue as outdated.

**Comment by Viditagarwal7479** [comment]
When thinking about crowdsourcing annotations, shouldn't we review the points in the issue and decide to reopen it if necessary? 
Instead of `Validator, ' we can have some other name like `CrowdSourced Annotater,` which might refer to a group of crowdsource annotators instead of a single person.
By this, when assigning a task to `CrowdSourced Annotater,` all the jobs in that task are assigned to them based on an internal algorithm that decides which job is assigned to which annotator. A single job is assigned to multiple annotators; similarly, an annotator would have multiple jobs to annotate.
